### ISSUE TITLE
Response field name is misspelled

### ISSUE THREAD

**Issue by jdeer0618** [bmacher/splunk-curl-command#1]
The response field name is spelled "reponse" and not "response".
<img width="429" alt="screen shot 2018-11-20 at 11 28 18 am" src="https://user-images.githubusercontent.com/4651176/48791531-8dfae300-ecb7-11e8-872d-b55ef19456bc.png">

**Comment by jdeer0618** [comment]
Unless, of course, this is a French spelling...

**Comment by bmacher** [comment]
Thanks for reporting the issue. I changed the code and it will be correct in the following release.
